name: 'Array API tests reporting'
description: 'Run the array API testsuite and report the results'
inputs:
  array-api-tests-module:
    description: 'Name of the namespace to run the array API testsuite against'
    required: true
    type: string
  array-library-install:
    description: "Command to install the array library"
    required: true
    type: string
  python-version:
    description: "Version of Python to run the testsuite on"
    required: false
    type: string
    default: "3.10"

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Checkout array-api-tests
      uses: actions/checkout@v3
      with:
        repository: data-apis/array-api-tests
        ref: "master"
        submodules: 'true'
        path: array-api-tests
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: "Install the array API tests test suite"
      run: install.sh
      shell: bash
    - name: "Install the array library"
      run: ${{ inputs.array-library-install }}
      shell: bash
    - name: "Run the array API test suite"
      run: test.sh ${{ inputs.array-api-tests-module }}
      shell: bash
    - name: "Upload JSON report artifact"
      uses: actions/upload-artifact@main
      with:
        name: json-report
        path: ${{ env.GITHUB_WORKSPACE }}/array-api-tests/.report.json

branding:
  icon: 'grid'
  color: 'blue'
